added moonraker_channel_updated flag
Cartographer3D/cartographer-klipper pull request #73
Opened 2024-11-19 13:41 UTC by krautech

## Description

Flag requirement to ensure moonraker.conf has been updated. This is temporarily in place to ensure the migration over to stable works.

`moonraker_channel_updated: True` if requirements are met

2024-11-19 13:56 UTC, Jomik requested changes

2024-11-19 13:56 UTC, Jomik commented on scanner.py
> +
Should we add a `TODO` comment?

2024-11-19 13:57 UTC, krautech commented on scanner.py
> +
more than likely

2024-11-19 14:01 UTC, krautech commented on scanner.py
> +
> Should we add a `TODO` comment?

Added

2024-11-19 14:02 UTC, Jomik approved these changes

2024-11-20 09:47 UTC, closed without merging

2024-11-20 09:47 UTC, Jomik commented
We don't want this after all.