Add types for config, printer and reactor
Cartographer3D/cartographer-klipper pull request #94
Opened 2024-11-21 22:22 UTC by Jomik

## Description

This creates a few type stubs for `ConfigWrapper`, `Printer` and `Reactor`.
This helps us infer proper types and catches some mistakes.
This will get rid of quite a few warnings, as well as ensure our integration is more stable in the future.

## Checklist

The following relevant macros have been tested:

- [ ] `CARTOGRAPHER_CALIBRATE`
- [ ] `PROBE`
- [ ] `PROBE_ACCURACY`
- [ ] `CARTOGRAPHER_THRESHOLD_SCAN`
- [ ] `CARTOGRAPHER_TOUCH CALIBRATE=1`
- [ ] `CARTOGRAPHER_TOUCH`
- [ ] `CARTOGRAPHER_TOUCH METHOD=manual`
- [ ] `BED_MESH_CALIBRATE`

2024-11-22 05:07 UTC, krautech commented
Should we merge this before or after the current code removal is done? @Jomik

2024-11-22 05:10 UTC, krautech requested changes
![image](https://github.com/user-attachments/assets/5c75aee7-3953-4a5c-81ba-797b5ddcfd64)

2024-11-22 06:21 UTC, Jomik commented
> Should we merge this before or after the current code removal is done? @Jomik 

After, as you can see, it hasn't been tested 😊

2024-11-23 10:42 UTC, krautech submitted a review, later dismissed

2024-11-23 11:12 UTC, krautech approved these changes

2024-11-23 11:33 UTC, merged